### ISSUE TITLE
URL remapping in Parser

### ISSUE THREAD

**Issue by tqchen** [rtfd/recommonmark#1]
It would be good to have a ability to remap url in the markdown reference during parsing. i.e. remap the internal link of .md .rst to suffix .html and external links to github. 

I used a hack to achieve this, which I think might be interesting to support to some extent in the original Parser.
https://github.com/dmlc/rabit/blob/master/doc/sphinx_util.py#L14

**Comment by lu-zero** [comment]
The parser right now converts the commonmark ast to docutils ast, probably there are already docutils facilities that can be wired in.

**Comment by tqchen** [comment]
resolved in #7
