### ISSUE TITLE
Markdown file, with links to other markdown files: how to make these links work?

### ISSUE THREAD

**Issue by aborruso** [rtfd/recommonmark#108]
Hi,
I'm building a RTD manual markdown based. Than first of all thank you for recommonmark!

I have a lot of md files, with this kind of links `[my text](myfile.md)`. 

But when I compile my RTD project, these link remain linked to the md files. I have in example `<a href="myfile.md">my text</a>` and not `<a href="myfile.html">my text</a>`.

Do I must change `[my text](myfile.md)` in `[my text](myfile.html)`? Is it the only way to use links to other markdown files in the repo?

Thank you

**Comment by pfultz2** [comment]
The links(which are not urls) in markdown are resolved by sphinx [`:any:`](http://www.sphinx-doc.org/en/stable/markup/inline.html#role-any) role, which lets you reference [`:doc:`](http://www.sphinx-doc.org/en/stable/markup/inline.html#role-doc):

>  Link to the specified document; the document name can be specified in absolute or relative fashion. For example, if the reference :doc:`parrot` occurs in the document sketches/index, then the link refers to sketches/parrot. If the reference is :doc:`/people` or :doc:`../people`, the link refers to people.

> If no explicit link text is given (like usual: :doc:`Monty Python members </people>`), the link caption will be the title of the given document.

**Comment by aborruso** [comment]
Hi @pfultz2 it's the first time I'm using sphinx, than I have a stupid question: in a markdown file, how do I must write links to other markdown files?
 
In this way `[Link text](:doc:/myMDfile)`?

Thank you

**Comment by pfultz2** [comment]
There is no need to put the role. It should just be `[Link text](/myMDfile)` or the relative path with `[Link text](myMDfile)`.

**Comment by aborruso** [comment]
Thank you
