### ISSUE TITLE
states.py not referenced through package in transform.py

### ISSUE THREAD

**Issue by romnempire** [rtfd/recommonmark#11]
when i try to run the test 'make html' locally, I get the error 

Exception occurred:
  File "/[REDACTED]/cats/recommonmark/transform.py", line 4, in <module>
    from states import DummyStateMachine
ImportError: No module named 'states'

I'm actually not a python person, so I don't know the inheritance/module mechanism at all, but if you change line 4 of recommonmark/transform.py to reference from `recommonmark.states` rather than from `states`, stuff works.

This seems like it's a titchy thing that might be environment dependent.  I'm also very confused.  Is this actually a bug and ...what's going on?

**Comment by romnempire** [comment]
Suspicion:  this is a python3 compatibility thing.

**Comment by tqchen** [comment]
I think you can change the line to
```
from .states import DummyStateMachine
```

**Comment by ericholscher** [comment]
Yea, this sounds like a Python 3 issue. We should be running our unit tests in Py2 & Py3, which would likely catch this bug.
