### ISSUE TITLE
Do not support HTML anchor link like "2018-05-11"

### ISSUE THREAD

**Issue by hengyunabc** [rtfd/recommonmark#117]
```
Release Notes
===

2018-05-11
----
* test
```

The HTML anchor link do not work.

I try to add some prefix, the work:

```
Release Notes
===

v2018-05-11
----
* test
```

**Comment by stsewd** [comment]
I think this is something related to the title begging with numbers, I think I saw this problem on rst too

**Comment by dholbach** [comment]
I think this is #8.
