### ISSUE TITLE
Can we have a new release, please?

### ISSUE THREAD

**Issue by jackjansen** [rtfd/recommonmark#127]
Can we have a new release of recommonmark, please? On my own machine I install from GitHub, which is no problem (once I found out that that worked:-), but when I want to build on readthedocs this is not an option.

(I'd specifically like the fix for linking to other .md files to work in the standard install).

**Comment by stsewd** [comment]
You can install directly from the repo using a `requirements.txt` file and https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

https://docs.readthedocs.io/en/latest/guides/specifying-dependencies.html

**Comment by ericholscher** [comment]
Yes, we should do a release, but it appears we still have bugs on Sphinx 1.8 that I want to fix. I can probably just do a release and do a point release to fix anything remaining though. 👍

**Comment by jackjansen** [comment]
@stsewd thanks, I've added a special requirements.txt to my project only for use on readthedocs (I don't want to pull all the sphinx stuff in for a normal install). That has solved my direct issue.

**Comment by ericholscher** [comment]
0.5.0 has been released.
