### ISSUE TITLE
Can't reference headings in a different file

### ISSUE THREAD

**Issue by gibfahn** [rtfd/recommonmark#155]
### Summary

I want to be able to reference a heading in a different file. In Github I would do this:

```markdown
[Guide Part 2](/path/to/guide.md#part-2)
```

### Full explanation

Let's say I have the file `path/to/guide.md` which looks like:

```markdown
# Guide

## Part 1

## Part 2
```

Linking to that doc via an absolute path (from a different file) works well:

```markdown
[Guide](/path/to/guide)
```

however, trying to link to a heading in that doc doesn't work, it gets resolved as an external reference:

```markdown
<!-- None of these work: -->
[Guide](/path/to/guide#part-2)
[Guide](/path/to/guide.md#part-2)
```

It does happen to work if you use `.html` and get the relative path right (but it's still resolved as an external link).

```markdown
[Guide](../../path/to/guide.html#part-2)
```

**Comment by gibfahn** [comment]
I guess a workaround might be to change `guide.md` to:

<pre>
# Guide

## Part 1

```eval_rst
.. _path/to/guide:part-2:

Part 2
======
```

</pre>

and then refer to it with:

```markdown
[Guide Part 2](path/to/guide:part-2)
```

But that's a bit complex. I'm hoping if https://github.com/sphinx-doc/sphinx/issues/6371 is resolved then simply enabling `autosectionlabel` will autogenerate the headings.

**Comment by idnsunset** [comment]
Does markdown itself support linking to an anchor in another file? As I know it only allows to link any anchor in the same page.

**Comment by gibfahn** [comment]
>Does markdown itself support linking to an anchor in another file?

Not sure about other flavours, but Github Formatted Markdown does, with the `[Guide Part 2](path/to/guide.md:part-2)` format.

**Comment by gibfahn** [comment]
>But that's a bit complex. I'm hoping if sphinx-doc/sphinx#6371 is resolved then simply enabling autosectionlabel will autogenerate the headings.

While trying to use this as a solution I hit another issue, in Sphinx a ref can have spaces in it, so <code>:ref:\`path/to/guide:part 2\`</code> is valid (and is what `autosectionlabel` generates). However I don't see a way to do that in recommonmark.

**Comment by idnsunset** [comment]
> Not sure about other flavours, but Github Formatted Markdown does, with the `[Guide Part 2](path/to/guide.md#part-2)` format.

Commonmark does not support it as nothing about this is mentioned in its spec.

**Comment by gibfahn** [comment]
>Commonmark does not support linking to heading in markdown files as nothing about this is mentioned in its spec.

I think the way it is supported in some implementations is that the html generator generates `id`s for the h1/h2/h3 tags, which means they can be referenced. You're right though, looks like Commonmark hasn't adopted this yet: https://talk.commonmark.org/t/feature-request-automatically-generated-ids-for-headers/115

**Comment by drrosa** [comment]
@gibfahn thanks for working on this issue! I upgraded to version `0.6.0` and Sphinx `2.2.0`. Then I followed the README instructions and syntax for [linking to headings in other files](https://github.com/readthedocs/recommonmark/blob/master/README.md#links), but it still doesn't work for me.

Are there any other extensions or settings that need to be enabled in `conf.py` for this to work?

I have tried both of the following link formats:
1. `[First Part](../path/to/guide.html#first)` --> `[First Part](../path/to/guide:first)`

2. `[first]: ../path/to/guide.html#first` --> `[first]: ../path/to/guide:first`

Do you have any sample conf.py and .md files that actually work using `sphinx.ext.autosectionlabel`? I'd really like to have a look at them as a sanity check.

**Comment by hackdna** [comment]
This did work for me as described in the docs. The trick with linking to sections that contain spaces was to URL-encode: `[link text](path/to/file_1:my%20section)`
