### ISSUE TITLE
Some markdown content doesn't internationalize properly

### ISSUE THREAD

**Issue by Bjwebb** [rtfd/recommonmark#21]
E.g. for https://github.com/Bjwebb/recommonmark-i18n-bug/blob/gh-pages/docs/index.md the messages I get pulled out by `sphinx-build -b gettext` are https://github.com/Bjwebb/recommonmark-i18n-bug/blob/gh-pages/_build/locale/index.pot - the bullet point is missing.

**Comment by Bjwebb** [comment]
Looks like this is because `.source` is `None` for some reason in the eventual doctree, and https://github.com/sphinx-doc/sphinx/blob/master/sphinx/util/nodes.py#L90 ignores such nodes.

**Comment by shimizukawa** [comment]
I think this issue has been fixed by #32

**Comment by Bjwebb** [comment]
This is fixed for the bullet points that were my original example.

Looks like eval_rst blocks don't internationalize, but I think that's quite different, so I've opened a new issue https://github.com/rtfd/recommonmark/issues/47
