### ISSUE TITLE
Lines in literal blocks are included twice

### ISSUE THREAD

**Issue by brechtm** [rtfd/recommonmark#22]
When parsing [CommonMark's README](https://github.com/jgm/CommonMark/blob/master/README.md) for example, each line in an indented code block is duplicated in the literal block in the docutils document tree.

**Comment by brechtm** [comment]
Caused by a bug in CommonMark-py. See https://github.com/rtfd/CommonMark-py/pull/37.

**Comment by lu-zero** [comment]
Thank you for fixing it!

**Comment by lu-zero** [comment]
Should be fixed now

**Comment by willingc** [comment]
@lu-zero I can confirm that there was no double output in my build yesterday (https://github.com/jupyter/jupyterhub/pull/368)
