### ISSUE TITLE
CommonMark 0.6.0 breaks compatibility

### ISSUE THREAD

**Issue by argaen** [rtfd/recommonmark#24]
Hi, it seems CommonMark (which was uploaded yesterday to pypi) breaks compatibility with this package. The error:

```
>>> from recommonmark.parser import CommonMarkParser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/manuelmiranda/.virtualenvs/docs/lib/python2.7/site-packages/recommonmark/parser.py", line 9, in <module>
    from CommonMark import DocParser, HTMLRenderer
ImportError: cannot import name DocParser
```

Forcing the installation of 0.5.4 works again. Tested with both 0.2.0 and 0.1.1 versions.

**Comment by tomck** [comment]
```
  File "conf.py", line 308, in <module>
    from recommonmark.parser import CommonMarkParser
  File "/www/readthedocs.org/user_builds/tbiodocs/envs/latest/lib/python2.7/site-packages/recommonmark/parser.py", line 5, in <module>
    from CommonMark import DocParser, HTMLRenderer
ImportError: cannot import name DocParser
```

I tried forcing 0.5.4 by changing the requirements/pip.txt for rtfd/readthedocs.org to include CommonMark==0.5.4, uninstalling 0.6.0 using pip, and installing 0.5.4 directly, but I still get this issue. Do you have a workaround?

**Comment by argaen** [comment]
Mmm? Have you tried that manually using the python terminal? By forcing the installation of the 0.5.4 package worked for me both in my local environment and in a RTD page (I had to write a requirements.txt file and tell my project to install the packages from that file).

Have you checked the build process? Maybe it is forcing the installation of 0.5.4 before it installs recommonmark which may be again installing a higher version.

**Comment by tomck** [comment]
I did try manually, but, I ended up just using a symlink so it would stop overwriting with 0.6.0, which was successful.

**Comment by paulci** [comment]
Is there a way to override this during the build process?  A single update would be a quick fix for now, until there's a proper resolution.

**Comment by paulci** [comment]
Updating tasks.py to include 'CommonMark==0.5.4' has worked for me.

**Comment by tomck** [comment]
Pardon my ignorance, but it does not seem to work for me. I updated tasks.py earlier and lately updated it to use capital letters in case that mattered, but it persists in believing that >=0.5.4 is good and as 0.6.1 came out and made my 0.6.0 symlink meaningless, I have resumed having issues.

        # Install requirements
        requirements = [
            'sphinx==1.3.1',
            'Pygments==2.0.2',
            'virtualenv==13.1.0',
            'setuptools==18.0.1',
            'docutils==0.11',
            'mkdocs==0.14.0',
            'mock==1.0.1',
            'pillow==2.6.1',
            'readthedocs-sphinx-ext==0.5.4',
            'sphinx-rtd-theme==0.1.9',
            'alabaster>=0.7,<0.8,!=0.7.5',
            'recommonmark==0.1.1',
            'CommonMark==0.5.4'
        ]
Do I need to place it earlier in the list or something?

**Comment by willingc** [comment]
@tomck Is there a reason that you have recommonmark pinned to 0.1.1?

I am getting clean imports with the changes that were pushed today by @ericholscher (Thanks Eric!). 
```
recommonmark==0.4.0
CommonMark==0.5.4
```
cc/@lu-zero FYI. Will test a bit more tommorrow.

**Comment by tomck** [comment]
No, ReadTheDocs has it pinned to 0.1.1 and I'm not having much luck with
altering what versions it likes.

**Comment by willingc** [comment]
@tomck Are you using the rtfd/ReadTheDocs.org repo for your build?
This is the requirements.txt file that ultimately is loaded for it
https://github.com/rtfd/readthedocs.org/blob/master/requirements/pip.txt

If you share a bit more about how you are set up, I may be able to help you workaround.

**Comment by tomck** [comment]
I am using a docker install actually, for reasons. The initial reason was, the docker install Just Works (tm).  https://hub.docker.com/r/vassilvk/readthedocs/

**Comment by willingc** [comment]
@tomck I would try editing this Dockerfile for your deployment if you are able. https://hub.docker.com/r/vassilvk/readthedocs/~/dockerfile/
You could insert lines in the Dockerfile:
```
# Install the required Python packages
RUN pip install -r requirements.txt

# Install a higher version of requests to fix an SSL issue
RUN pip install requests==2.6.0

# Install a different version of recommonmark
RUN pip install recommonmark==0.4.0
```

**Comment by paulci** [comment]
@tomck I also am using docker, although building rtd through the dockerfile.  I added CommonMark above recommonmark in the list.  I added it to tasks.py in a running container to test.  My dockerfile copies the custom task.py during build, to ensure I always have the same settings.

Dockerfile
COPY docker/fixes/tasks.py $RTD_DIR/readthedocs/projects/tasks.py

tasks.py
        # Install requirements
        requirements = [
            'sphinx==1.3.1',
            'Pygments==2.0.2',
            'virtualenv==13.1.0',
            'setuptools==18.0.1',
            'docutils==0.11',
            'mkdocs==0.14.0',
            'mock==1.0.1',
            'pillow==2.9.0',
            'readthedocs-sphinx-ext==0.5.4',
            'sphinx-rtd-theme==0.1.9',
            'alabaster>=0.7,<0.8,!=0.7.5',
            'CommonMark==0.5.4',
            'recommonmark==0.1.1',
        ]

**Comment by tomck** [comment]
@willingc I did [exactly this](https://github.com/tomck/readthedocs-docker/commit/3e647664630b9426a52637859d23f29a0db43e9b#diff-3254677a7917c6c01f55212f86c57fbf), [rebuilt and re-deployed](https://hub.docker.com/r/tomck/readthedocs-docker/builds/b9wzs9wenapqw5xf4ha9cwb/), and it is still trying to use 0.1.1.

```
python /www/readthedocs.org/user_builds/read-the-docs/envs/stable/bin/pip install --use-wheel -U --cache-dir /www/readthedocs.org/user_builds/read-the-docs/.cache/pip sphinx==1.3.1 Pygments==2.0.2 virtualenv==13.1.0 setuptools==18.0.1 docutils==0.11 mkdocs==0.14.0 mock==1.0.1 pillow==2.6.1 readthedocs-sphinx-ext==0.5.4 sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5 recommonmark==0.1.1
...
Requirement already up-to-date: commonmark>=0.5.4 in ./user_builds/read-the-docs/envs/stable/lib/python2.7/site-packages (from recommonmark==0.1.1)
```

**Comment by willingc** [comment]
@tomck Bah to the first part. It looks like the installation of recommonmark 0.1.1 does not pin its dependency to commonmark==0.5.4 but instead any release greater than 0.5.4 which would explain why 0.6.1 is being installed.

Glad the second part is working for you. :smiley:

**Comment by alasdairdc** [comment]
I've got RTD deployed to a server and have changed the files `requirements/pip.txt` and `readthedocs/projects/tasks.py` to `'recommonmark==0.4.0',` and removed the file `readthedocs/projects/tasks.pyc` but I when building it seems to ignore this and still fails.  Any thoughts?

**Comment by willingc** [comment]
@alasdairdc Awesome :sunny:

**Comment by MinchinWeb** [comment]
On my computer, I've found that using CommonMark-py v0.5.5 (that last release before v0.6.0) works as well.

In regards to the 0.6.0 changes, it seems that it has brought a significant reworking of the AST (see [this comment](https://github.com/rtfd/CommonMark-py/issues/45#issuecomment-168994047) for some details). I don't understand enough of what is going on to fix it myself, but hopefully someone else will find this helpful.
