### ISSUE TITLE
Release with updated CommonMark support

### ISSUE THREAD

**Issue by effigies** [rtfd/recommonmark#78]
The latest recommonmark [release](https://pypi.python.org/pypi/recommonmark/0.4.0) requires `CommonMark <= 0.5.4`, which is too old for some other packages (for my purposes, specifically [sphinx-argparse](https://github.com/ribozz/sphinx-argparse/blob/master/setup.py#L41)). This is causing ReadTheDocs builds to fail.

Would it be possible to do a release with more recent CommonMark support that was recently added?

**Comment by ericholscher** [comment]
I can try and get this released -- have you tried installing from master and confirming it works on your side?

**Comment by effigies** [comment]
Thanks for looking into this.

The only place I've encountered the issue is in RTD's environment, which I haven't replicated. I can spend some time on that if it's worth doing.

**Comment by CJ-Wright** [comment]
When you release can you please include the license in the pypi package? It is needed to make a conda-forge package.

**Comment by leotrs** [comment]
I'm having the exact same issue as @effigies -- also trying to use sphinx-argparse.

**Comment by lexual** [comment]
I'm guessing @CJ-Wright might be already across it.

But this is causing conda-forge version of recommonmark to be broken, as they only have recent commonmark versions packaged, and until a release occurs, it fails.

**Comment by lexual** [comment]
Can confirm installing from master, resolves problem.

**Comment by ericholscher** [comment]
0.5.0 is out now, so this should be fixed.
