### ISSUE TITLE
PyPI version

### ISSUE THREAD

**Issue by tdomhan** [rtfd/recommonmark#92]
The PyPI version seems to be fairly out of date (2016) and still rely on commonmark <= 0.5.4, while master seems to have been updated already. Would it be possible that you upload a current version to PyPI?

**Comment by tdomhan** [comment]
More concretely I have the issue that commonmark needs CommonMark <= 0.5.4, while sphinx-argparse needs version >= 0.5.6.

**Comment by h-hirokawa** [comment]
+1.
Are there any release blockers?

**Comment by edmorley** [comment]
Please can a new version be released to PyPI?

**Comment by nsoranzo** [comment]
FYI recommonmark 0.5.0 has been released yesterday on PyPI.

**Comment by edmorley** [comment]
Many thanks!

**Comment by ericholscher** [comment]
Sorry for the delay here. We will be quicker with this in the future, it was just hard to juggle a few version incompatibilities.

**Comment by tdomhan** [comment]
great, thanks!
